export enum ExpensesTableEnum {
    OPER_ID = 'operId',
    OBJECT_ID = 'objectId',
    STATUS = 'status',
    BUY_SELL = 'buySell',
    EXTERNAL_ID = 'externalId',
    DOCUMENT_ID = 'documentId',
    CLIENT_CONTRACT_ID = 'clientContractId',
    EVENT_ID = 'eventId',
    IIS = 'isIIS',
    CLIENT_ID = 'clientId',
    ASSET_ID = 'assetId',
    ASSET_NAME = 'assetName',
    ISIN = 'isin',
    ACTUAL_DATE = 'actualDate',
    EVENT_QTY = 'eventQty',
}